#!/bin/sh
LOCK_FILE=/var/run/org.osx86.localtime-toggle.lock

to_utc() {
	echo "localtime-toggle: Toggling to UTC."
	date -f %m%d%H%M%Y `date -u +%m%d%H%M%Y`
}

to_localtime() {
	echo "localtime-toggle: Toggling to localtime."
	date -u -f %m%d%H%M%Y `date +%m%d%H%M%Y`
}

touch_lock() {
	if [ -f $LOCK_FILE ]; then
		echo 'localtime-toggle: Run lock exist.'
	else
		echo "localtime-toggle: Touch run lock."
		touch $LOCK_FILE
		sleep 5
	fi
}

touch_lock
trap 'to_localtime; exit' term
to_utc
{ while true; do sleep 86400; done; } &
wait
